#!/usr/bin/env python3
import sys

class PositionIsTooLargeError(Exception):
    """Too big"""
    pass

try:
    position = int(sys.argv[1]) # Capture file in-arguement
    inFile = sys.argv[2] # Catpture position in-arguement

    strFile = ""
    lines = open(inFile, "r").readlines() # Read lines from file

    # Make lines into one string for search:
    for line in lines:
        strFile += line
    if position > len(strFile):
        raise PositionIsTooLargeError
        
    # Find beginning of line:
    lineStart = ""
    forwardCount = 1
    while True:
        if strFile[position - forwardCount] == '\n':
            break
        lineStart = strFile[position - forwardCount] + lineStart
        forwardCount += 1

    # Find end of line:
    lineEnd = ""
    backwardCount = 1
    while True:
        lineEnd += strFile[position + backwardCount]
        if strFile[position + backwardCount] == '\n':
            break
        backwardCount += 1

    # Join the parts:
    lineContent = lineStart + strFile[position] + lineEnd
    lineWithHighlight = lineStart + "[-> " + strFile[position] + " <-]" + lineEnd

    # Find line number, then show result:
    for idx, line in enumerate(lines):
        if lineContent in line :
            print(str(idx + 1) + ":", lineWithHighlight)

except PositionIsTooLargeError:
    print("Error: Position is is greater than the character count of the file.")
except:
    print("Error: Double check that your in-arguements are in this form: ./cph 150 filename.cs")
